# Generated by Django 5.1.3 on 2025-01-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0002_userfollows"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(default="default_username", max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
