# Generated by Django 5.1.3 on 2025-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0003_customer_username_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
