# Generated by Django 5.1.3 on 2024-12-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="app.ticket"),
        ),
    ]
